GET http://localhost:5001/users
 
### 
POST http://localhost:5001/login
Content-Type: application/json

{
    "username": "Lucas", 
    "password": "1234"
}

###
GET http://localhost:5001/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJ1c2VybmFtZSI6Ikx1Y2FzIiwiaWF0IjoxNzEzNjU5MjgxLCJleHAiOjE3MTM2NjI4ODF9.oEzu5oMTxsUxCXnVnHoWTvX2LlG5TIqQLqm7eg2Fb18

###
GET http://localhost:5001/news
