name: CI Workflow

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    #- name: Run backend tests
    #  run: npm run test-backend  

    #- name: Run frontend tests
    #  run: cd frontend && npm install && npm test  

    - name: Build frontend
      run: npm run build-frontend
